</body>
<script type="application/ld+json">
    {
        "@context": "https://schema.org",
        "@type": "",
        "name": "",
        "url": "",
        "sameAs": [
            "https://twitter.com/"
        ],
        "address": {
            "@type": "PostalAddress",
            "streetAddress": "",
            "addressRegion": "",
            "postalCode": "",
            "addressCountry": "FR"
        }
    }
</script>