<?php
namespace App\Controllers;

use Core\Controllers\Controller;

/**
 * Class BlogController
 * @package App\Controllers
 */
class BlogController extends Controller
{

    const ADD_NEW_POST_ROUTE = "new";

    /**
     * BlogController constructor.
     *
     * @param $path
     * @param null $params
     */
    public function __construct($path, $params = null)
    {
        if ($params) {
            if ($params[0] === self::ADD_NEW_POST_ROUTE) {
                $path .= '.new';
            }
        }
        parent::__construct($path, $params);
    }

    public function beforeRender()
    {
        $this->setStylesheetPath('blog.css');
        parent::beforeRender(); // TODO: Change the autogenerated stub
    }

}