<?php
namespace App\Controllers;

use App\App;
use App\Entity\PostEntity;
use App\Models\PostModel;
use Core\Controllers\Controller;

/**
 * Class IndexController
 * @package App\Controllers
 */
class IndexController extends Controller
{

    /**
     * @var PostEntity[]
     */
    public $lastArticles;

    public function beforeRender()
    {
        /** @var PostModel $postModel */
        $postModel = App::getModel('post');
        $this->lastArticles = $postModel
            ->setLimit(3)
            ->setOrderBy('created_at', 'DESC')
            ->getCollection();
        parent::beforeRender(); // TODO: Change the autogenerated stub
    }

}