<?php
namespace App\Controllers;

use App\App;
use App\Entity\UserEntity;
use App\Models\UserModel;
use App_Core_Exception;
use Core\Controllers\Controller;
use Core\Utils\Ajax;
use Core\Utils\Request;

/**
 * Class LoginController
 * @package App\Controller
 */
class LoginController extends Controller
{

    const LOGIN_REQUEST_TYPE = "login";

    /**
     * @var Request
     */
    protected $request;

    /**
     * @var UserModel
     */
    protected $userModel;

    public function __construct($path, $params = null)
    {
        $this->request = new Request();
        $this->userModel = App::getModel('user');
        parent::__construct($path, $params);
    }

    /**
     * @throws App_Core_Exception
     */
    public function beforeRender()
    {
        $this->checkPostRequest();
        $this->setStylesheetPath('login.css');
        $this->setScriptPath('login.js', true);
        parent::beforeRender(); // TODO: Change the autogenerated stub
    }

    /**
     * Check post request
     * @throws App_Core_Exception
     */
    public function checkPostRequest()
    {
        if (!$this->request->isPost()) return;
        $ajaxObject = new Ajax($this->request->getPost());
        switch ($ajaxObject->getRequestType()) {
            case self::LOGIN_REQUEST_TYPE:
                $datas = $ajaxObject->getRequestDatas();
                /** @var UserEntity $loginUser */
                $loginUser = $this->userModel->getEntity($this->userModel->_entityName, [
                    'email'         => $datas['email'],
                    'password'      => $datas['password']
                ]);

                // Check if email exist email
                /** @var UserEntity $user */
                if ($user = $this->userModel->load($loginUser->getEmail(), 'email')) {
                    if ($user->getPassword() === $loginUser->getPassword()) {
                        $ajaxObject->success("Connecté !");
                    } else {
                        $ajaxObject->error("Mot de passe incorect");
                    }
                } else {
                    $ajaxObject->error("Cet adresse mail n'existe pas");
                }



                if ($user)

                $created = $this->userModel->create($user, $this->userModel->_tableName);
                $created ?
                    $ajaxObject->success("Vous êtes bien inscrit !") :
                    $ajaxObject->error("Une erreur c'est produite, veuillez réessayer");
        }
        $ajaxObject->sendResponse();
    }

}