<?php
namespace App\Controllers;

use Core\Controllers\Controller;

/**
 * Class RegisterController
 * @package App\Controller
 */
class RegisterController extends Controller
{

    public function beforeRender()
    {
        $this->setStylesheetPath('register.css');
        parent::beforeRender(); // TODO: Change the autogenerated stub
    }

}