<?php
namespace App\Controllers;

use App\App;
use App\Entity\UserEntity;
use App\Models\UserModel;
use Core\Controllers\Controller;
use Core\Utils\Request;

/**
 * Class RegisterController
 * @package App\Controller
 */
class RegisterController extends Controller
{

    const REGISTER_REQUEST_TYPE = "register";

    /**
     * @var Request
     */
    protected $request;

    public function __construct($path, $params = null)
    {
        $this->request = new Request();
        parent::__construct($path, $params);
    }

    public function beforeRender()
    {
        $this->checkPostRequest();
        $this->setStylesheetPath('register.css');
        $this->setScriptPath('register.js', true);
        parent::beforeRender(); // TODO: Change the autogenerated stubs
    }

    /**
     * Check post request
     */
    public function checkPostRequest()
    {
        if ($this->request->isPost()) {
            switch ($this->request->getPost('type')) {
                case self::REGISTER_REQUEST_TYPE:
                    /** @var UserModel $userModel */
                    $userModel = App::getModel('user');

                    $datas = $this->request->getPost();
                    $user = $userModel->getEntity('user', [
                        'name'          => $datas['username'],
                        'email'         => $datas['email'],
                        'password'      => $datas['password'],
                        'created_at'    => time()
                    ]);
                    $created = $userModel->create($user, $userModel->_tableName);
                    $created ?
                        $this->result['success'] = "Vous êtes bien inscrit !" :
                        $this->result['error'] = "Une erreur c'est produite, veuillez réessayer";
            }
            echo json_encode($this->result);
            exit;
        }
    }

}