<?php
/** @var Render $this */
use App\App;
use App\Controllers\BlogController;
use App\Models\UserModel;
use Core\Utils\Render;

/** @var BlogController $blogController */
$blogController = $this->class;
$article = $blogController->article;

/** @var UserModel $userModel */
$userModel = App::getModel('user');
$userLogged = $userModel->getUserSession();
?>
<div class="container p-5">
    <div class="post-preview">
        <h2 class="fw-bolder darky fst-italic uppercase">
            <?= $article->getTitle() ?>
        </h2>
        <p class="text-muted">
            <?= $article->getContent() ?>
        </p>
        <p class="darky">
            Posté par
            <a class="text-capitalize" href="<?= App::getHost() . '/profile/' . $article->getAuthorId() ?>">
                <?= $article->getAuthor()->getName() ?>
            </a>
            le <?= date('d/m/Y', $article->getCreatedAt()) ?> à
            <span class="text-muted"><?= date('H:i', $article->getCreatedAt()) ?></span>
        </p>
    </div>
    <div class="d-flex">
        <?php if ($userLogged && $userLogged->getId() === $article->getAuthorId()): ?>
            <a href="<?= App::getHost() . '/blog/' . $article->getUrlKey() . '/edit' ?>" type="button" class="btn btn-primary">Editer l'article</a>
            <a href="<?= App::getHost() . '/blog/' . $article->getUrlKey() . '/delete' ?>" type="button" class="btn btn-danger mx-2">Supprimer l'article</a>
        <?php endif; ?>
    </div>
</div>
