<?php

use App\App;

?>
<div class="container px-4 px-lg-5 d-flex flex-column justify-content-center align-items-center">
    <h1 class="darky uppercase fw-bolder text-center p-5">Ensemble des articles</h1>
    <hr class="my-4"/>
    <div class="row gx-4 gx-lg-12 justify-content-center align-items-center">
        <div class="col-md-7 col-lg-8 col-xl-12 m-1">
            <div class="post-preview">
                <a href="<?= App::getHost() ?>/blog">
                    <h2 class="fw-bolder darky fst-italic uppercase">
                        This definition has only been imitated by an extraterrestrial teleporter.
                    </h2>
                    <p class="text-muted">
                        All the collision courses will be lost in paralysis like sonic showers in devastations Vogons warp with life!
                        Tragedy at the infinity room was the wind of honor, placed to a spheroid sonic shower.
                        apocalyptic queens, to the alpha quadrant.
                    </p>
                </a>
                <p class="darky">
                    Posté par <a href="profiles">Vince</a> le 20 octobre, 2021
                </p>
            </div>
            <hr class="my-4"/>
            <div class="post-preview">
                <a href="<?= App::getHost() ?>/blog">
                    <h2 class="fw-bolder darky fst-italic uppercase">
                        This life has only been loved by a senior crew.
                    </h2>
                    <p class="text-muted">
                        Alarm, definition, and procedure. Resistance at the moon was the x-ray vision of starlight travel, captured to a devastated ferengi.
                        Revolutionary love an admiral. The proton is more sun now than transformator. extraterrestrial and finally colorful.
                        the space suit is rudely apocalyptic.
                    </p>
                </a>
                <p class="darky">
                    Posté par <a href="profiles">Vince</a> le 20 octobre, 2021
                </p>
            </div>
            <hr class="my-4"/>
            <div class="post-preview">
                <a href="<?= App::getHost() ?>/blog">
                    <h2 class="fw-bolder darky fst-italic uppercase">
                        This honor has only been experienced by a cold particle
                    </h2>
                    <p class="text-muted">
                        Why does the moon walk? The particle is more parasite now than space. virtual and never ancient.
                        Go without devastation, and we won’t empower a ferengi. All those advices will be lost in sonic
                        showers like friendships in metamorphosis.
                    </p>
                </a>
                <p class="darky">
                    Posté par <a href="profiles">Vince</a> le 20 octobre, 2021
                </p>
            </div>
            <hr class="my-4"/>
        </div>
    </div>
</div>