<?php
/** @var Render $this */
use App\App;
use App\Controllers\BlogController;
use Core\Utils\Render;

/** @var BlogController $blogController */
$blogController = $this->class;
?>
<div class="container px-4 p-5 d-flex flex-column justify-content-center align-items-center">
    <h1 class="darky uppercase fw-bolder text-center p-5">Ensemble des articles</h1>
    <hr class="my-4"/>
    <div class="row gx-4 gx-lg-12 justify-content-center align-items-center">
        <div class="col-md-7 col-lg-8 col-xl-12 m-1">
            <?php foreach ($blogController->articles as $article): ?>
                <div class="post-preview">
                    <a href="<?= App::getHost() . '/blog/' . $article->getUrlKey() ?>">
                        <h2 class="fw-bolder darky fst-italic uppercase">
                            <?= $article->getTitle() ?>
                        </h2>
                        <p class="text-muted">
                            <?= $article->getResume() ?>
                        </p>
                    </a>
                    <p class="darky">
                        Posté par
                        <a class="text-capitalize" href="<?= App::getHost() . '/profile/' . $article->getAuthorId() ?>">
                            <?= $article->getAuthor()->getName() ?>
                        </a>
                        le <?= date('d/m/Y', $article->getCreatedAt()) ?> à
                        <span class="text-muted"><?= date('H:i', $article->getCreatedAt()) ?></span>
                    </p>
                </div>
                <hr class="my-4"/>
            <?php endforeach; ?>
        </div>
    </div>
</div>