<?php

use App\App;
use App\Controllers\IndexController;
use App\Models\UserModel;

/** @var IndexController $indexController */
$indexController = $this->class;

/** @var UserModel $userModel */
$userModel = App::getModel('user');
$userLogged = $userModel->getUserSession();
?>
<div style="background: url(https://bootstrapious.com/i/snippets/sn-static-header/background.jpg)" class="bg-cover text-white bg-opacity-75">
    <div class="d-flex justify-content-center align-items-center flex-column container vh-50 text-center">
        <h1 class="display-4 fw-bolder uppercase">Conception d'un blog en PHP</h1>
        <p class="fst-italic mb-0 bg-dark-opacity rounded w-50">Projet OpenClassrooms qui consiste à développer un blog professionnel.</p>
    </div>
</div>
<div class="container px-4 px-lg-5">
    <div class="row gx-4 gx-lg-5 justify-content-center">
        <h1 class="darky uppercase fw-bolder text-center p-5">Articles récents</h1>
        <div class="col-md-10 col-lg-8 col-xl-7">
            <?php foreach ($indexController->lastArticles as $article): ?>
                <div class="post-preview">
                    <a href="<?= App::getHost() . '/blog/' . $article->getUrlKey() ?>">
                        <h2 class="fw-bolder darky fst-italic uppercase"><?= $article->getTitle() ?></h2>
                    </a>
                    <p class="darky">
                        Posté par
                        <a class="text-capitalize" href="<?= App::getHost() . '/profile/' . $article->getAuthorId() ?>">
                            <?= $article->getAuthor()->getName() ?>
                        </a>
                        le <?= date('d/m/Y', $article->getCreatedAt()) ?> à
                        <span class="text-muted"><?= date('H:i', $article->getCreatedAt()) ?></span>
                    </p>
                </div>
                <hr class="my-4" />
            <?php endforeach; ?>
            <div class="d-flex justify-content-end mb-4">
                <a class="btn btn-primary text-uppercase" href="<?= App::getHost() ?>/blog">plus de posts →</a>
            </div>
        </div>
    </div>
</div>