<?php

/** @var ProfileController $profileController */

use App\App;
use App\Controllers\ProfileController;

$profileController = $this->class;
?>
<div class="content vh-90">
    <div class="container p-5 m-5 d-flex justify-content-center flex-column">
        <div class="row">
            <div class="text-center card-box">
                <div class="member-card pt-2 pb-2">
                    <div class="thumb-lg member-thumb mx-auto">
                        <img src="<?= App::getHost() ?>/public/assets/img/empty.png" class="rounded-circle img-thumbnail" alt="profile-image">
                    </div>
                    <div class="">
                        <h4><?= $profileController->user->getName() ?></h4>
                        <p class="text-muted"><?= $profileController->user->getEmail() ?></p>
                    </div>
                    <div class="mt-4">
                        <div class="row">
                            <div class="col-4">
                                <div class="mt-3">
                                    <h4 class="uppercase fw-bolder"><?= date('d/m/Y', $profileController->user->getCreatedAt()) ?> à
                                        <span class="text-muted"><?= date('H:i', $profileController->user->getCreatedAt()) ?></span>
                                    </h4>
                                    <p class="mb-0 text-muted">Date de création</p>
                                </div>
                            </div>
                            <div class="col-4">
                                <div class="mt-3">
                                    <h4 class="uppercase fw-bolder"><?= count($profileController->user->getArticles()); ?></h4>
                                    <p class="mb-0 text-muted">Nombre d'article(s) écrit</p>
                                </div>
                            </div>
                            <div class="col-4">
                                <div class="mt-3">
                                    <h4 class="uppercase fw-bolder"><?= count($profileController->user->getComments()); ?></h4>
                                    <p class="mb-0 text-muted">Nombre de commentaire(s) écrit</p>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- end row -->
    </div>
    <!-- container -->
</div>